const userManagementSelection = {
  userImg: document.querySelector('.user-avatar-lg'),
  userName: document.querySelector('.user-name'),
  userEmail: document.querySelector('.user-email'),
  emailInput: document.getElementById('email'),
  userRole: document.querySelector('.user-role-badge'),
  btnDelete: document.querySelector('.btn-delete'),
  profileAvatar: document.getElementById('profileLabel'),
  activeButton: document.getElementById('activeBtn'),
  blockedButton: document.getElementById('blockedBtn'),
  pendingButton: document.getElementById('pendingBtn'),
  btnEdit: document.querySelector('.btn-edit'),
  activeManagerGrid: document.querySelector('#showActiveUser'),
  blockedManagerGrid: document.querySelector('#showBlockedUser'),
  pendingManagerGrid: document.querySelector('#showPendingUser'),
  emptyBlockedSection: document.getElementById('emptyBlocked'),
  createdAt: document.querySelector('.created-at'),
  updatedAt: document.querySelector('.updated-at'),
  managerView: document.querySelectorAll('.manager-list-section'),
  confirmUpdate: document.querySelector('#confirmUpdate'),
  profileImg: document.querySelector('#profileImg'),
  addManagerForm: document.getElementById('addManagerForm'),
  addManagerBtn: document.querySelector('.add-manager-btn'),
  toggleBtns: document.querySelector('.btn-group'),
  name: document.getElementById('name'),
  updateProfileForm: document.querySelector('#updateProfile'),
  toastSection: document.getElementById('toastSection'),
  lastLogin: document.getElementById('lastLogin'),
  warehouseSection: document.getElementById('showWarehouses'),
};

export default userManagementSelection;
